### ISSUE TITLE
A bug in FakeRoutingApi.Defer method

### ISSUE THREAD

**Issue by rsivanov** [rebus-org/Rebus.TestHelpers#1]
Hi

It seems that you have an error in FakeRoutingApi.Defer method. 
The current code:
 var messageSentToDestination = _factory.CreateEventGeneric<MessageDeferredToDestination>(
                typeof(MessageSentToDestination<>),
                explicitlyRoutedMessage.GetType(),
                destinationAddress,
                delay,
                explicitlyRoutedMessage,
                optionalHeaders
            );

There should be typeof(MessageDeferredToDestination<>) instead of typeof(MessageSentToDestination<>).

**Comment by mookid8000** [comment]
oh good catch! Thanks for reporting it 😄 would you like to fix it and submit a pull request?

**Comment by mookid8000** [comment]
fixed by #2 – available in Rebus.TestHelpers 5.2.1

thanks for reporting & fixing 👍
