### ISSUE TITLE
Rebus 8 update broke saga test

### ISSUE THREAD

**Issue by Qball1337** [rebus-org/Rebus.TestHelpers#14]
I noticed that my shiny saga test broke while updating to Rebus 8. I have a saga test where i test an Ifailed handler (the regular handler is not part of the saga) and i see an handler not found exception :( 

Testing an ifailed where the regular handler is part of the saga does work tho. With testing i mean using the deliverFailed method.

This worked with Rebus 7.

**Comment by mookid8000** [comment]
Oh that does not sound like something that was supposed to happen! 😅

Could you show me some more details? I.e. what does your test do? And please include the full exception details. 🙂

**Comment by mookid8000** [comment]
Hi @Qball1337 , just came across this very old issue. Lots of stuff has been fixed since you raised it, so I assume that the problem went away. If not, please let me know 🙂
